#spring.application.name=rabbitMQ-app
spring.application.name=spring-boot-rabbitMQ
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
management.endpoints.web.exposure.include=health,info,beans
rabbitMQ.name=welcome.rabbitMQ.queue
rabbitMQ.direct.exchange=welcome.rabbitMQ.exchange
rabbitMQ.direct.exchange.route.key=direct.exchange.route.key
